### PR TITLE
PTW-119 and 120: camelcase php properties and ensure default searched for key fields

### PR DESCRIPTION
**Pull request by peterchallett**

### CODE REVIEW

**Comment by TomEdwards** [comment]
@peterchallett holding off this PR pending short conversation - I think the approach looks good but I have a feeling it may be safer to not go this way. Annotations referencing fields look like things might get a bit more complex

**Comment by TomEdwards** [comment]
@peterchallett please can we add camelize onto field names within annotations

**Comment by peterchallett** [comment]
@TomEdwards Updated to handle comment fields with snake or camel case. Sorry about Namespace rename mixed in :/

**Review by TomEdwards — APPROVED** [review]
Looks good, renames from OnCorps to ApiPlatform for specialisations and camelize is applied to field names

**Pull request merged**
